name: Failing Workflow

on:
  workflow_dispatch:

jobs:
  build-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Intentionally fail
        run: |
          echo "This will fail"
          exit 1
