name: Failing Workflow

on:
  workflow_dispatch:

jobs:
  build-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run failing command
        run: |
          echo "❌ This will fail"
          exit 1  # Force a failure here
